[2022-11-15 16:53:21,425] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: DAG_Minio_S3_Wait_for_File.DownloadFileFromS3 scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2022-11-15 16:53:21,481] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: DAG_Minio_S3_Wait_for_File.DownloadFileFromS3 scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2022-11-15 16:53:21,484] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-11-15 16:53:21,485] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-11-15 16:53:21,486] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-11-15 16:53:21,577] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): DownloadFileFromS3> on 2022-11-14 00:00:00+00:00
[2022-11-15 16:53:21,592] {standard_task_runner.py:52} INFO - Started process 1639 to run task
[2022-11-15 16:53:21,613] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'DAG_Minio_S3_Wait_for_File', 'DownloadFileFromS3', 'scheduled__2022-11-14T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/sensor.py', '--cfg-path', '/tmp/tmpgxvn2noa', '--error-file', '/tmp/tmpadkp88af']
[2022-11-15 16:53:21,618] {standard_task_runner.py:80} INFO - Job 25: Subtask DownloadFileFromS3
[2022-11-15 16:53:21,975] {task_command.py:371} INFO - Running <TaskInstance: DAG_Minio_S3_Wait_for_File.DownloadFileFromS3 scheduled__2022-11-14T00:00:00+00:00 [running]> on host 73a41ac08797
[2022-11-15 16:53:22,379] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Maico Bernal
AIRFLOW_CTX_DAG_ID=DAG_Minio_S3_Wait_for_File
AIRFLOW_CTX_TASK_ID=DownloadFileFromS3
AIRFLOW_CTX_EXECUTION_DATE=2022-11-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-14T00:00:00+00:00
[2022-11-15 16:53:22,421] {base.py:68} INFO - Using connection ID 'minio_conn' for task execution.
[2022-11-15 16:53:22,426] {base_aws.py:210} INFO - Credentials retrieved from extra_config
[2022-11-15 16:53:26,460] {s3.py:857} INFO - Downloading source S3 file from Bucket data with path precios234.csv
[2022-11-15 16:53:26,575] {base.py:68} INFO - Using connection ID 'minio_conn' for task execution.
[2022-11-15 16:53:26,587] {base_aws.py:210} INFO - Credentials retrieved from extra_config
[2022-11-15 16:53:28,034] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/sensor.py", line 49, in DownloadAndRenameFile
    file_name = hook.download_file(key=key, bucket_name=bucket_name, local_path=path)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 63, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 91, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 869, in download_file
    with NamedTemporaryFile(dir=local_path, prefix='airflow_tmp_', delete=False) as local_tmp_file:
  File "/usr/local/lib/python3.7/tempfile.py", line 547, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/local/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/to_transform/airflow_tmp_b3day9nz'
[2022-11-15 16:53:28,175] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=DAG_Minio_S3_Wait_for_File, task_id=DownloadFileFromS3, execution_date=20221114T000000, start_date=20221115T165321, end_date=20221115T165328
[2022-11-15 16:53:28,300] {standard_task_runner.py:97} ERROR - Failed to execute job 25 for task DownloadFileFromS3 ([Errno 2] No such file or directory: '/opt/airflow/data/to_transform/airflow_tmp_b3day9nz'; 1639)
[2022-11-15 16:53:28,460] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-11-15 16:53:29,101] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
